version: '3'
services:
  agent:
    build: ./../mlis-agent
    image: mlis_agent
    links:
    - server
    - pytorch
    environment:
    - ADMIN_TOKEN
    - GRAPHQL_URL=$PRODUCTION_AGENT_GRAPHQL_URL
    volumes:
    - ./../mlis-agent:/usr/src/app
    - /var/run/docker.sock:/var/run/docker.sock
    command: npm run start
  server:
    build: ./../mlis-server
    image: mlis_server
    ports:
    - "80:8000"
    - "443:8443"
    links:
    - database
    environment:
    - APP_ID
    - APP_SECRET
    - JWT_SECRET
    - HOSTNAME
    - INIT_DATA
    volumes:
    - ./../mlis-server:/usr/src/app
    - ./../mlis-pytorch/mlis/problems:/usr/src/problems
    command: npm run start
  pytorch:
    build: ./../mlis-pytorch
    image: mlis_pytorch
  database:
    image: postgres:alpine
    volumes:
    - ./.database:/var/lib/postgresql/data
    - ./.backups:/usr/src/backups
